name: Deploy client to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/expense-tracker-client:0.0.1.RELEASE .
      - name: Push image to docker
        run: docker push ${{ secrets.DOCKER_USERNAME }}/expense-tracker-client:0.0.1.RELEASE

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/expense-tracker-client:0.0.1.RELEASE
      #   - name: Stop old container
      #     run: docker stop client
      #   - name: Remove old container
      #     run: docker rm client
      - name: Run docker container
        run: docker run -d -p 4000:80 --name client ${{secrets.DOCKER_USERNAME}}/expense-tracker-client:0.0.1.RELEASE
